name: Update project structure
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # at the end of every day
{% raw %}
jobs:
  auto-update-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install dependencies
        run: pip install "cruft[pyproject]" poetry jello

      - name: Update project structure
        run: |
          cruft update -y

      - name: Check if there are changes
        id: changes
        run: echo "::set-output name=changed::$(git status --porcelain | wc -l)"

      - name: Apply additional changes and fixes
        if: steps.changes.outputs.changed > 0
        run: |
          poetry lock --no-update  # add new dependencies
          poetry install
          poetry run pre-commit run -a || true  # we have to fix other issue manually

      - name: Get new template version
        if: steps.changes.outputs.changed > 0
        # extract new cookiecutter template version
        run: |
          echo "TEMPLATE_COMMIT=$(cat .cruft.json | jello -r "_['commit'][:8]")" >> $GITHUB_ENV
      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour

      - name: Create Pull Request
        if: steps.changes.outputs.changed > 0
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_GITHUB_TOKEN }}
          commit-message: >-
            Update project structure using cruft to ${{ env.TEMPLATE_COMMIT }}
          title: "[Actions] Auto-sync cookiecutter template"
          body: ""
          branch: automatic/cookiecutter-update
          delete-branch: true
{% endraw %}
