on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy
{% raw %}
jobs:
  deployment:
    name: 'Deploy to PROD'
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSHKEY }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PORT: ${{ secrets.PORT }}
      - name: Clone repo
        run: |{% endraw %}
          ssh production 'cd ~/Coding/ && git clone git@github.com:{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}.git | true'
{% raw %}
      - name: Reset to latest main
        if: ${{ always() }}|{% endraw %}
        run: |
          ssh production 'cd ~/Coding/{{cookiecutter.project_slug}} && git fetch && git reset --hard origin/main'
      - name: Stop containers
        run: |
          ssh production 'docker ps -q --filter ancestor="{{cookiecutter.project_slug}}" | xargs -r docker stop'
      - name: Build image
        run: |
          ssh production 'cd ~/Coding/{{cookiecutter.project_slug}} && docker build . -t {{cookiecutter.project_slug}}'
      - name: Start container
        run: |
          ssh production 'docker run -it -d --net=host {{cookiecutter.project_slug}}:latest'
