name: Publish docs

on:
  push:
    branches:
      - main
{% raw %}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force{% endraw %}
